import {useStore} from 'react-redux';
import {Employee} from '../interface/employee.interface.ts';

/**
 * This hook is used to add an employee to the store
 */
export default function useEmployeeStore() {
    const store = useStore();
    // WARN NOT GOOD : timestamps are added to be unique, but this will start again to 2000 is app is reloaded
    // think about removing this and use a real unique id generated by DB when having a backend
    let idIncrement: number = 2000;

    const addEmployee = (employee: Employee) => {
        idIncrement++;
        return store.dispatch({
            type: 'ADD_EMPLOYEE',
            payload: {...employee, id: `${idIncrement}${new Date().getTime()}`}
        });
    };
    return {addEmployee};
}
